### ISSUE TITLE
215 - Bad Authentification data

### ISSUE THREAD

**Issue by ThomasMilhau** [twitterdev/SnowBotDev#3]
Hi,
When I start setup_welcome_messages.rb with heroku, I get this error. The oauth is broken ?

`Getting welcome message list.
GET ERROR occurred with /1.1/direct_messages/welc
ome_messages/list.json:
Error: #<Net::HTTPBadRequest:0x0000000001f53e48>
{"errors":[{"code":215,"message":"Bad Authenticat
ion data."}]}
Message IDs:
./scripts/setup_welcome_messages.rb:224:in <main>: undefined method 'each' for nil:NilClass (NoM
ethodError)`

Thank for helping me :(

**Comment by ThomasMlh** [comment]
And the same thing for setup_webhooks.rb...

`Setting a webhook configuration...
POST ERROR occurred with /1.1/account_activity/webhooks.json?url=https%3A%2F%2Flegacybotdm.herokuapp.com%2Flegacybotdm, request:
Error code: 400 #<Net::HTTPBadRequest:0x0000000002250358>
Error Message: {"errors":[{"code":215,"message":"Bad Authentication data."}]}
{"code"=>215, "message"=>"Bad Authentication data."}`
